### PR TITLE
Job Search Fixes

### PR DESCRIPTION
**Pull request by kushp**
### In Short
I have fixed job searching, adding to shortlist, deleting shortlisted jobs.

### Technical Details
There were a lot of JobMine object changes from the JobMine update, I have listed them here:
* There was a PeopleSoft JS library used called 'net', it was replaced with 'net2'
* The popupObj_win0 object was replaced with MOpopupObj_win0
* window.top.ptrc was replaced with window.top.ptRC2
* hAction_win0 function was replaced with submitAction_win0

### CODE REVIEW

**Comment by kushp** [comment]
Update: I just retested the delete shortlisted jobs single (not multi-delete) function and looks like that works too now.

**Comment by matthewn4444** [comment]
So you tested delete single and multiple? I can't test it personally so I probably take your word for it.

**Comment by kushp** [comment]
Do you have Skype ? You could teamviewer me and check it out. But yeah both single and multiple delete seem to work. When I initially fixed it, it appeared like only multiple delete was working but I just retested it and both seem to be working.

**Comment by kushp** [comment]
I may have spoke too soon, it appears that single delete works if you do it after doing a multiple delete.

**Comment by matthewn4444** [comment]
When you get it to work properly I can accept the pull request. I will probably remove some useless code after and fix the update codes.

**Comment by kushp** [comment]
I think I got it to work properly, it was a timing issue of some sorts.
Deleting single items got as far as this code
```
               BRIDGE.run(function(){
                     setSaveText_win0('Saving...');
                     submitAction_win0(document.win0, '#ICSave');
               });
```
However, ajax complete never got called back with #ICSave as it should. But if I called submitAction again on the chrome console while it was stuck at deleting the item then it would work fine. So, I added a small timeout inside that run, submitAction executes a bit later and ajax complete gets called, everything seems fine. We should monitor user feedback on this, but I think deleting from short list be fixed for good. 

In my latest commit I also replaced your ContentLoader.finalCall override. I looked at it and I looked at the updated version on jobmine site and it looked like the original function had changed. So I took the new finalCall function and modified it to handle removing the annoying added to shortlist popups. then replaced the entire override with that. 

You can accept the pull request now/review code.

**Comment by matthewn4444** [comment]
Did you test this with Firefox and Greasemonkey?

**Comment by kushp** [comment]
Just tested using newest Firefox and Greasemonkey, for some reason it doesn't work.
However, it does work with Firefox and Scriptish as you mentioned in your original installation steps here https://github.com/matthewn4444/jobmine-plus-extension/wiki/Firefox.

**Comment by matthewn4444** [comment]
Is it possible to fix it in Greasemonkey? Scriptish is depreciated and old. What kind of issues exist? Visual or functional?

**Comment by kushp** [comment]
Visually it looks fine. However, stuck at loading after hitting search and stuck at loading after deleting. It looks like for whatever realize the submitAction_win0 function isn't working with Greasemonkey, but it works fine with Scriptish. I don't know what differences there are between the two that would cause that. No useful error messages in the console.

**Comment by matthewn4444** [comment]
Can you send me the updated version you have and I can see if I can still do a search and debug the issue.

**Comment by kushp** [comment]
Do you have access to JobMine ? 
The most up to date version I have is here https://github.com/kushp/jobmine-plus-extension/blob/master/jobmine_plus.user.js

**Comment by matthewn4444** [comment]
I have login and view access only. I can do a search but it will always return an error, I think you said greasemonkey just doesn't search? I cannot shortlist or apply to jobs and removing items remove permanently. 

I did update the app a few weeks ago and I haveb no idea if changes in jobmine broke anything. The changes I saw was a search text was changed (id tag) and ic_action or something isn't sent back from the server anymore.

I will look into this tonight when I get back.

**Comment by kushp** [comment]
GreaseMonkey will hang on search just like it did before my updates and it would also hang when you try deleting from shortlist, but if you manage to fix the hang on search in GreaseMonkey then the hang on deleting from shortlist would be fixed too.

**Comment by matthewn4444** [comment]
I added a patch (git apply ....) to fix bridge, seems that greasemonkey blocks it or something. This file is so old because I was using javascript url redirects, I actually rewrote this class for another project to use events, but too much to fix to implement the new one in this so I applied a quick fix for greasemonkey.

After patching please test on chrome and firefox (since I cannot search jobs etc). 

Also I would appreciate if you can possibility edit the files under  **/build/src/** and then run the python script to build it, it make coding this more organized even if there is more steps.

Once you finished this I can merge the pull request.

[fix.zip](https://github.com/matthewn4444/jobmine-plus-extension/files/265593/fix.zip)

**Comment by kushp** [comment]
I tested on chrome and Firefox, it works on GreaseMonkey now with your patch. How'd you figure that out? Is there a secret GreaseMonkey log that records when functions are blocked ? 

I did edit the /build/src files! Check files modified in my commits. Yeah I didn't run the python script though.

Commit your patch then merge the pull request!

**Comment by cgada** [comment]
Been testing this on chrome for a bit. The search by location doesn't seem to working either.

**Comment by matthewn4444** [comment]
kushp, the issue was related to something I wrote back a long time ago so I knew there would have been an issue for that, it would have been hard for someone new to debug it.

Anyways I committed my patch. I would like if you are about to edit the individual files from /build/src and then run ./build.py or node build.js to build the userscript instead of modifying it directly to avoid merge issues. When you sync your branch to mine you will might get merge issues.

**Comment by kushp** [comment]
@cgada Location is a weird dilemma. I can get the drop-down to populate but for some reason the location submitted always remains the same as the one selected from the magnifying glass thing even though the JavaScript code that sets the location element's value to selected location from drop-down works. We should close this pull request and open location filtering as a new issue.

@matthewn4444 I will do that moving forward. I'll probably delete my userscript.js file before syncing with your branch, the updates are in the /build/src/ when you merge this pull request so I can rebuild the script after syncing after you pull.

**Comment by matthewn4444** [comment]
@cgada Agreed, new issue should be placed. May look into that if you guys can't figure it out (probably an ajax issue if Waterloo changed their site, which they did).

@kushp After you do that I can change some parts of the code to remove the old update code I added back a long time ago since irrelevant because greasemonkey, tampermonkey and scriptish uses @updateUrl now. After that we should look into the location.

**Comment by kushp** [comment]
@matthewn4444 after I do what ? I was saying this pull request already has modified /src/build/ files containing my fixes. So when you merge you can ignore my jobmine_plus.user.js file completely if there are conflicts and the updates will be there. Then make your changes and build it then I can sync after that.

**Comment by matthewn4444** [comment]
Oh sorry about that I will do this when I get home from work.

**Comment by kushp** [comment]
sweet!

**Comment by cgada** [comment]
sgtm @kushp @matthewn4444 I'll look into the location thing when I get some time.

**Comment by matthewn4444** [comment]
Ok I am done with this for now, I added more cleanup

**Pull request merged**
