### PR TITLE
Changed the highlighting of "On Short List" to coral, for a more dist…

### PR DESCRIPTION
**Pull request by sarimzafar**
Changed the highlighting of "On Short List" to coral, for a more disinct and a better view.

### CODE REVIEW

**Comment by sarimzafar** [comment]
UI Updates

**Comment by matthewn4444** [comment]
The reason I kept it the same color was so that you didn't have to care about that item since it was on short list or applied already, so the same color allows you to visually sort as is. I don't think this is a valid submission unless more people want this.

**Comment by sarimzafar** [comment]
That does makes sense, I thought it would be a little more visually appealing.

**Comment by matthewn4444** [comment]
You can keep it on yours and just package it for other people if they want
it. Thanks anyways.

**Comment by sarimzafar** [comment]
Hey Matthew, on a second thought I think it makes sense to keep them of two different colours. Suppose, a job can be on your short list but you may or may not have applied to it. They don't really fall under the same category as Cancelled/Rejected. Let me know what you think.

**Pull request closed without merging**
